#!/usr/bin/env ruby
require 'rubygems'
require 'bundler/setup'
require 'mailman'

Mailman.config.logger = Logger.new("log/mailman.log")

Mailman.config.pop3 = {
  server: 'pop.gmail.com', port: 995, ssl: true,
  username: "courserarails@gmail.com",
  password: "test@1234"
}

Mailman::Application.run do
  default do
    begin
      Comment.receive_mail(message)
    rescue Exception=>e
      Mailman.logger.error "Exception occurred while receiving message:\n#{message}"
      Mailman.logger.error [e, *e.backtrace].join("\n")
    end
  end	
end